# **2주차 Percentron 기초**

In [8]:
import numpy as np
import pandas as pd
import matplotlib 


In [11]:
def AND(x):
    w =np.array([.5,.5])
    theta= 0.7
    sigma= np.dot(x,w)      # 같은 위치에 있는 것을 곱하고 서로 더한다
    if sigma > theta:
        return 1
    else:
        return 0

input = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
for i in input:
    print(i, ":", AND(i))

[0 0] : 0
[0 1] : 0
[1 0] : 0
[1 1] : 1


In [13]:
input = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
for i in input:
    x=np.array([i[0],i[1],1])
    print(x)

[0 0 1]
[0 1 1]
[1 0 1]
[1 1 1]


In [17]:
def act( s):
    if s>0:
        return 1
    else:
        return 0
def pep(x,w):
    sigma = np.dot(x,w)
    return act(sigma)
def AND(x):
    X=np.array([x[0],x[1],-1])
    W=np.array([.5,.5,.8])
    return pep(X,W)
def OR(x):
    X=np.array([x[0],x[1],-1])
    W=np.array([.5,.5,.4])
    return pep(X,W)
def NAND(x):
    X=np.array([x[0],x[1],-1])
    W=np.array([.5,.5,.8])
    return pep(X,-W)
input = np.array([[0,0],
                  [0,1],
                  [1,0],
                  [1,1]])
print("AND GATE")
for i in input:
    print(i , ":", AND(i))
print("OR GATE")
for i in input:
    print(i , ":", OR(i))
print("NAND GATE")
for i in input:
    print(i , ":", NAND(i))

AND GATE
[0 0] : 0
[0 1] : 0
[1 0] : 0
[1 1] : 1
OR GATE
[0 0] : 0
[0 1] : 1
[1 0] : 1
[1 1] : 1
NAND GATE
[0 0] : 1
[0 1] : 1
[1 0] : 1
[1 1] : 0
